language: cpp

compiler:
- gcc
- clang

before_install:  
  # g++
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  # clang
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

install:
  - sudo apt-get update

  -
    if [[ "${CXX}" == "g++" ]]; then
      sudo apt-get install -y g++-4.8; export CXX="g++-4.8";
    fi
  
  -
    if [[ "${CXX}" == "clang++" ]]; then
      sudo apt-get install -y clang-3.6; export CXX="clang++-3.6";
    fi

script:
  - "bash -c ./test.sh"