language: cpp

compiler:
- gcc
- clang

before_install:  
  # g++
  - if [ "$CXX" == "g++" ]; then sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test; fi
  # clang
  - if [ "$CXX" == "clang++" ]; then sudo add-apt-repository -y ppa:h-rayflood/llvm; fi

install:
  - sudo apt-get update

  # Install package dependencies.
  - sudo apt-get install -y $LLVM_PACKAGE "clang-$CLANG_VERSION" libconfig++8-dev python-sphinx libboost-program-options1.55-dev libboost-regex1.55-dev libboost-system1.55-dev libboost-filesystem1.55-dev libcsfml-dev texlive-latex-recommended texlive-fonts-recommended texlive-latex-extra

  # Install a recent version of g++ to build the compiler (with C++11 support).
  -
    if [[ "${CXX}" == "g++" ]]; then
      sudo apt-get install -y g++-4.8; export CXX="g++-4.8";
    fi

  # Use a recent version of clang++ to build the compiler (with C++11 support);
  # use the previously installed clang version (since installing one tends to remove another).
  -
    if [[ "${CXX}" == "clang++" ]]; then
      export CXX="clang++-$CLANG_VERSION";
    fi

script:
  - "bash -c ./test.sh"